### ISSUE TITLE
Export Compatibility Issues

### ISSUE THREAD

**Issue by ckorhonen** [mariusandra/insights#5]
Experimenting with Insights on our one of our Rails 4.2 app - when I run `rake insights:export` I am seeing a lot of failures, with both polymorphic associations, and in places where I'm using the `friendly_id` and `acts_as_taggable` (which are themselves using polymorphic associations under the hood).

``` ruby
NoMethodError: undefined method `primary_key' for ActsAsTaggableOn::Taggable:Module
```

Also see an issue with the `closure_tree` gem - it creates `_hierarchies` tables without a primary key, which results in this message:

``` ruby
Unknown primary key for table foo_hierarchies in model FooHierarchy.
```

**Comment by mariusandra** [comment]
Hey, thanks for trying it out! :)

I haven't used those gems myself, but I'm not too surprised to see bugs here. I would gladly merge fixes to [`insights_export`](https://github.com/mariusandra/insights_export) if you could provide them... or more debug info, e.g. which lines break... and which changes make them not break.

It should be quite easy to hack on it as the [entire export script](https://github.com/mariusandra/insights_export/blob/master/lib/insights_export/export_models.rb) is just one file.

Thanks!

**Comment by serra92** [comment]
Hey,

I've been also having issues with polymorphic relations. I'm using a polymorphic relation in my models and I keep getting this error when i try to export my active record:

uninitialized constant Attachment::Attachable

**Comment by mariusandra** [comment]
Hey, 

I got `acts_as_taggable_on` working with 0.2.2 of `insights_export`. It's not super pretty, but works. Just like with other `has_many` associations, you have to click into the `through` part manually:

<img width="1522" alt="screen shot 2017-06-06 at 08 08 24" src="https://cloud.githubusercontent.com/assets/53387/26816016/d49bc390-4a8f-11e7-94c5-e66572ce9110.png">

I also added a slightly more graceful failure handling. Now the script should export all the models it can and print errors for those it can't. Thus you'll at least have some `insights.yml` file at the end.

I didn't have time to fully check polymorphic models yet. That's still to do.
